Mount Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Import Libraries

In [ ]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

Load Data

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/AI Data/Ageremoved_dataset.csv")
data.head()

phone  Laptop  TV  Headaches  Blurry vision  Specs
0      6       4   1          0              0      0
1      9       5   1          1              1      1
2      6       3   1          0              0      0
3     10       2   0          1              1      1
4     10       0   4          0              0      1

Data Split

In [ ]:
#split dataset in features and target variable
feature_cols = ['phone', 'Laptop', 'TV', 'Headaches', 'Blurry vision']
X = data[feature_cols] 
y = data.Specs

In [ ]:
# Split dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

Random Forest Model Training

In [ ]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 3, criterion="entropy")  
classifier.fit(X_train, y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=3)

FOR TRAINING DATA

In [ ]:
#Predicting the test set result  
y_pred= classifier.predict(X_train) 

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_train, y_pred)
cm  

array([[74,  3],
       [ 2, 95]])

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy entropy training:",metrics.accuracy_score(y_train, y_pred))

Accuracy entropy training: 0.9712643678160919


FOR TESTING DATA

Prediction

In [ ]:
#Predicting the test set result  
y_pred= classifier.predict(X_test)  

Model Metrics

In [ ]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm  

array([[32,  6],
       [ 4, 33]])

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy entropy testing:",metrics.accuracy_score(y_test, y_pred))

Accuracy entropy testing: 0.8666666666666667


Random Forest Model Training gini

In [ ]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 3, criterion="gini")  
classifier.fit(X_train, y_train)  

RandomForestClassifier(n_estimators=3)

Training Data Prediction gini

In [ ]:
#Predicting the test set result  
y_pred= classifier.predict(X_train) 

In [ ]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_train, y_pred)
cm

array([[72,  5],
       [ 2, 95]])

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy gini training ",metrics.accuracy_score(y_train, y_pred))

Accuracy gini training  0.9597701149425287


Testing Data

In [ ]:
#Predicting the test set result  
y_pred= classifier.predict(X_test) 

In [ ]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
cm  

array([[30,  8],
       [ 5, 32]])

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy gini testing",metrics.accuracy_score(y_test, y_pred))

Accuracy gini testing 0.8266666666666667


Save the Model

In [ ]:
import pickle
# Save the model
filename = 'random_forest_model.pkl'
pickle.dump(classifier, open(filename, 'wb'))

# Depth based accuracy using entropy

Training

In [ ]:
# Create Decision Tree classifer object
classifier = RandomForestClassifier(criterion="entropy", max_depth=4)

# Train Decision Tree Classifer
classifier = classifier.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = classifier.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8933333333333333


Deployment

In [ ]:
list_of_columns = data.columns
input_data=pd.DataFrame(columns=list_of_columns)
input_data.drop(['Specs'], axis='columns', inplace=True)

input_data.at[0, 'phone'] = float(input('phone = '))
input_data.at[0, 'Laptop'] = float(input('Laptop = '))
input_data.at[0, 'TV'] = float(input('TV = '))
input_data.at[0, 'Headaches'] = int(input('Headaches (1/0) '))
input_data.at[0, 'Blurry vision'] = int(input('Blurry vison (1/0) '))
y_pred =  classifier.predict(input_data)

if(y_pred[0]==1):
  print('You need Specs')
if(y_pred[0]==0):
  print('You dont need Specs')

phone = 5
Laptop = 3
TV = 4
Headaches (1/0) 1
Blurry vison (1/0) 1
You need Specs
